name: vexora_api

services:
  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
  vexora:
    build: .
    restart: always
    ports:
      - "5555:5555"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST_IP=host.docker.internal
      - MOOD_DETECTION_URL=http://host.docker.internal:8000/mood-detection
    develop:
      watch:
        - path: ./
          action: rebuild
    depends_on:
      - redis
    links:
      - redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
  model:
    build:
      context: .
      dockerfile: api/Vexora-Model/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - HOST_IP=host.docker.internal
