name: vexora_api

services:
  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
  vexora:
    build: .
    restart: always
    ports:
      - "5555:5555"
    develop:
      watch:
        - path: ./
          action: rebuild
    depends_on:
      - redis
    links:
      - redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]